https://blog.paperspace.com/intro-to-optimization-momentum-rmsprop-adam/

In [41]:
import keras

In [42]:
from keras.datasets import mnist
#MNIST dataset downloaded in image format and already converted to categorical data

(features_train, labels_train), (features_test, labels_test) = mnist.load_data() #60000/10000 - training and testing data

In [43]:
print(features_train.shape) #60000, 28, 28
print(labels_train.shape) #10000, 28, 28
print(features_test.shape) #60000,
print(labels_test.shape) #10000,

(60000, 28, 28)
(60000,)
(10000, 28, 28)
(10000,)


In [44]:
print(features_train[0].shape) #28, 28
print(features_train[0][0].shape) #28,

(28, 28)
(28,)


In [45]:
features_train[9]
features_train[12][0]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0], dtype=uint8)

In [46]:
labels_train

array([5, 0, 4, ..., 5, 6, 8], dtype=uint8)

In [ ]:
features_test[0]

In [48]:
labels_test

array([7, 2, 1, ..., 4, 5, 6], dtype=uint8)

In [49]:
features_train = features_train.reshape((60000, 28, 28, 1)) #reshaping - 60000 images, widht/height known. we have to provide depth-1

In [50]:
features_train.shape #60000, 28, 28, 1

(60000, 28, 28, 1)

In [ ]:
features_train[0]

In [53]:
#feature scaling - min/max scaling, range: [0-1]
features_train = features_train.astype('float32') / 255 

In [ ]:
features_train[10]

In [ ]:
#testing data - feature scaling
features_test.shape #10000, 28, 28
features_test = features_test.reshape((10000, 28, 28, 1))

features_test = features_test.astype('float32') / 255

features_test[0]

In [56]:
from tensorflow.keras.utils import to_categorical

labels_train = to_categorical(labels_train, num_classes=10, dtype='float32')
labels_test = to_categorical(labels_test, num_classes=10)

In [57]:
print(labels_train.shape)
labels_train[0]

(60000, 10)


array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0.], dtype=float32)

In [58]:
print(labels_test.shape)
labels_test[0]

(10000, 10)


array([0., 0., 0., 0., 0., 0., 0., 1., 0., 0.], dtype=float32)

In [59]:
from keras import layers
from keras import models

In [88]:
model = models.Sequential() #empty sequential model - now going to add
model.add(layers.Conv2D(32, (3, 3), activation = 'relu', input_shape = (28, 28, 1))) #node, filter - 3*3/5*5, activation function, input shape of image - width*height*depth (depth --> grey-1, color-3)
model.add(layers.MaxPooling2D((2, 2)))
model.add(layers.Conv2D(16, (5, 5), activation = 'relu')) #Conv2D - fixed pixels for all images, for different pixel images we have to use Conv3D
model.add(layers.MaxPooling2D((2, 2)))

#Now, flattening after two times repeating convolution/max_pooling
model.add(layers.Flatten())

#ANN
model.add(layers.Dense(64, activation='relu')) #nodes,activation function
model.add(layers.Dense(10, activation='softmax')) #nodes - equal to number of classes which is from 0 to 9/last layer, activation function - softmax/multiclass classification

In [63]:
#Compiling - optimize it (rmsprop, adam), loss function, accuracy metrics
model.compile(optimizer='rmsprop',loss='categorical_crossentropy',metrics=['accuracy'])

model.fit(features_train, labels_train, epochs=50, batch_size=64)

Epoch 1/50
938/938 [==============================] - 44s 46ms/step - loss: 0.2273 - accuracy: 0.9310
Epoch 2/50
938/938 [==============================] - 43s 46ms/step - loss: 0.0721 - accuracy: 0.9773
Epoch 3/50
938/938 [==============================] - 43s 46ms/step - loss: 0.0503 - accuracy: 0.9846
Epoch 4/50
938/938 [==============================] - 44s 46ms/step - loss: 0.0384 - accuracy: 0.9879
Epoch 5/50
938/938 [==============================] - 43s 46ms/step - loss: 0.0317 - accuracy: 0.9904
Epoch 6/50
938/938 [==============================] - 43s 46ms/step - loss: 0.0259 - accuracy: 0.9920
Epoch 7/50
938/938 [==============================] - 43s 46ms/step - loss: 0.0220 - accuracy: 0.9929
Epoch 8/50
938/938 [==============================] - 43s 46ms/step - loss: 0.0187 - accuracy: 0.9941
Epoch 9/50
938/938 [==============================] - 43s 46ms/step - loss: 0.0169 - accuracy: 0.9948
Epoch 10/50
938/938 [==============================] - 43s 46ms/step - loss: 0.014

In [64]:
test_loss, test_accuracy = model.evaluate(features_test, labels_test) #loss and accuracy

313/313 [==============================] - 3s 8ms/step - loss: 0.1256 - accuracy: 0.9892


In [65]:
features_test[0].shape

(28, 28, 1)

In [66]:
print('Test accuracy is:',test_accuracy)

Test accuracy is: 0.9891999959945679


In [67]:
model.layers

In [68]:
type(features_train)

numpy.ndarray

In [69]:
features_train[10].shape

(28, 28, 1)

In [70]:
testing_data = features_train[10].reshape(1,28,28,1)

In [71]:
testing_data.shape

(1, 28, 28, 1)

In [75]:
import numpy as np
np.argmax(model.predict(testing_data), axis=-1) #for multi-class classification/softmax function
#Set axis=-1 means, extract largest indices in each row. Here we have only one row.

array([3])

In [76]:
labels_train[10]

array([0., 0., 0., 1., 0., 0., 0., 0., 0., 0.], dtype=float32)

In [77]:
labels_train[10].argmax()

3

In [78]:
"""
Website for better understanding:
https://medium.com/coinmonks/handwritten-digit-prediction-using-convolutional-neural-networks-in-tensorflow-with-keras-and-live-5ebddf46dc8
"""

'\nWebsite for better understanding:\nhttps://medium.com/coinmonks/handwritten-digit-prediction-using-convolutional-neural-networks-in-tensorflow-with-keras-and-live-5ebddf46dc8\n'

In [79]:
features_test.shape

(10000, 28, 28, 1)

In [80]:
test_data = features_test

In [91]:
predictions = np.argmax(model.predict(test_data), axis=-1) #for multi-class classification/softmax function

In [ ]:
list(zip(predictions, labels_test.argmax(axis=1)))

In [90]:
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(labels_test.argmax(axis=1), predictions) #10*10

print(cm)

[[ 973    1    0    0    0    2    1    1    2    0]
 [   0 1131    0    0    0    0    1    2    0    1]
 [   2    1 1020    1    1    0    0    7    0    0]
 [   0    0    2 1003    0    3    0    1    1    0]
 [   0    0    1    0  978    0    1    0    0    2]
 [   1    0    1    4    0  882    1    1    1    1]
 [   5    2    0    1    4    1  944    0    1    0]
 [   0    2    3    0    0    0    0 1021    0    2]
 [   5    0    3    2    0    1    0    2  960    1]
 [   2    3    0    3   10    6    0    3    2  980]]
